# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_notifiable',
            field=models.BooleanField(default=False),
        ),
    ]
